'use client'

import { createContext, useContext, useState, type ReactNode } from 'react'

export type Locale = 'de' | 'en' | 'ru'

const translations = {
  de: {
    nav: { sound: 'Sound ↔ Skin', spectrum: 'Spektrogramm', shape: 'SHAPE', dna: 'DNA', contact: 'Kontakt', start: 'Projekt starten', aria: 'Hauptnavigation', language: 'Sprache wählen' },
    hero: { eyebrow: 'SHAPE YOUR SOUND', arts: 'Musik · Kunst · Klangform', audience: 'Für Musiker:innen & Labels', title: 'Wir machen Klang', titleEnd: 'sichtbar', signal: '01 · Signal', frequency: 'Frequenz', alt: 'Abstraktes Spektrogramm mit Frequenzbändern und Schallwellen', intro: 'Agentur für Künstler:innen und Labels. Wir lesen Spektrogramme, zerlegen Frequenzen und geben dem Sound eine', emphasis: 'Form, die bleibt.', discuss: 'Projekt besprechen →', spectrum: 'Spektrogramm' },
    process: { label: '[ Arbeitsweise ]', title: 'Vom Signal zur Welle', intro: 'Drei Bewegungen, ein durchgehendes Signal — von der ersten Analyse bis zur lebendigen Community.', steps: [ ['01', 'Zuhören / Lesen', 'Sound und Spektrogramm lesen. Den Charakter hören, bevor eine einzige Linie entsteht.', 'Analyse'], ['02', 'Zerlegen & Formen', 'Frequenzen und Bild zerlegen, neu als tragfähige Form zusammensetzen.', 'System'], ['03', 'Die Welle starten', 'System, Content und Community werden zu einer Bewegung.', 'Release'] ], accent: 'VON DIR\nFÜR ALLE.' },
    sound: { label: 'Sound ↔ Skin', title: 'Tätowierung und Schallwelle', subtitle: 'Beide sind Spur einer Vibration', body: 'Schall ist organisierte Schwingung. Die Tätowiermaschine ebenfalls. Unterschied nur in der Materie: Luft oder Haut. Beides verwandelt Frequenz in', emphasis: 'dauerhafte Form.', alt: 'Blackwork-Tätowierung, die in eine Schallwelle übergeht', cue: 'tippen / hören', mapping: [['Frequenz', 'Linienstärke'], ['Amplitude', 'Kontrast / Füllung'], ['Rhythmus', 'Wiederholung & Pause'], ['Stille', 'Negativraum']], metrics: [['20 Hz – 20 kHz', 'hörbares Spektrum'], ['∞', 'bleibt auf der Haut'], ['1 → 2', 'ein Signal, zwei Medien']] },
    analyse: { label: 'Analyse', title: 'Spektrogramm als Design-Brief', intro: 'Wir lesen das Spektrogramm nicht als Dekoration, sondern als Bauplan. Jede Frequenzzone wird zur Design-Entscheidung: Dichte, Linie, Rhythmus, Leerraum.', bands: [['01 · LOW', 'Bass / Fundament', 'Schwere, lange Formen. Breite Linien, große Flächen — outer contour im Blackwork.'], ['02 · MID', 'Körper / Charakter', 'Rhythmus und Textur. Wiederholung, Modulation — hier entsteht der „Sound“ der Marke.'], ['03 · HIGH', 'Detail / Glanz', 'Feine Spitzen und Highlights. Dünne Linien, sparsame Akzente.']] },
    shape: { label: 'New Branch · 2026', title: 'SHAPE YOUR SOUND', intro: 'Einer der jüngsten Entwicklungszweige. Wir visualisieren das Klangbild der Clients und bauen Systeme für Cover, Motion, Stage und Identity.', alt: 'Visuelles Identitätssystem aus Spektrogramm-Formen, Covern und Motion-Frames', cards: [['VISUAL SOUND', 'Klang sichtbar machen', 'Spektrogramm → Form. Waveform und Frequenzräume für visuelle Identität.'], ['FORM + SYSTEM', 'Form und System', 'Vom Release bis zur gesamten visuellen Welt eines Artists.']], pillars: [['01 · Musik', 'Lebendiger Klang\nund sein Publikum', 'Release-Strategien, visuelle Systeme, Konzerte und Community um Artist oder Label.'], ['02 · Kunst & Kreativität', 'Rahmen für\nden Künstler', 'Vom Manifest bis zur tragfähigen Community. Klar sprechen und die Richtigen versammeln.']] },
    dna: { label: '[ System DNA ]', people: [['DEVELOPER · I/TD', 'imtryingtodesign', 'Technische Architektur und Design-System. Baut die strukturierte Seite — Systeme, die Performance und Form zusammenhalten.', 'imtryingtodesign.com →'], ['SPIRITUAL EXPEDITOR', 'NAMENLOS TATTOO', 'Zerlegt in Komponenten, um neu zusammenzusetzen. Roh, präzise — nimmt auseinander, was später als Ganzes auf der Haut trägt.', 'NAMENLOS →']] },
    contact: { label: 'Kontakt', title: 'Release, Klang oder Form?', intro: 'Erzähl uns, was du schaffst. Antwort innerhalb von', hours: '24 Stunden.', received: 'Signal empfangen', thanks: 'Danke — wir lesen dein Spektrogramm und melden uns innerhalb von 24 Stunden.', name: 'Name / Projekt', namePlaceholder: 'Artist, Label oder Release', email: 'E-Mail', message: 'Nachricht', messagePlaceholder: 'Erzähl uns von deinem Sound…', send: 'Anfrage senden →' },
    footer: { aria: 'Fußnavigation', links: ['Sound ↔ Skin', 'Spektrogramm', 'DNA', 'Kontakt'] },
  },
  en: {
    nav: { sound: 'Sound ↔ Skin', spectrum: 'Spectrogram', shape: 'SHAPE', dna: 'DNA', contact: 'Contact', start: 'Start a project', aria: 'Main navigation', language: 'Select language' },
    hero: { eyebrow: 'SHAPE YOUR SOUND', arts: 'Music · Art · Soundform', audience: 'For musicians & labels', title: 'We make sound', titleEnd: 'visible', signal: '01 · Signal', frequency: 'Frequency', alt: 'Abstract spectrogram with frequency bands and sound waves', intro: 'An agency for artists and labels. We read spectrograms, break down frequencies and give sound a', emphasis: 'form that lasts.', discuss: 'Discuss a project →', spectrum: 'Spectrogram' },
    process: { label: '[ Our process ]', title: 'From signal to wave', intro: 'Three movements, one continuous signal — from the first analysis to a living community.', steps: [ ['01', 'Listen / Read', 'Read the sound and its spectrogram. Hear its character before a single line exists.', 'Analysis'], ['02', 'Deconstruct & Shape', 'Break down frequency and image, then rebuild them as a resilient form.', 'System'], ['03', 'Start the wave', 'System, content and community become a movement.', 'Release'] ], accent: 'FROM YOU\nFOR ALL.' },
    sound: { label: 'Sound ↔ Skin', title: 'Tattoo and soundwave', subtitle: 'Both are traces of vibration', body: 'Sound is organized vibration. So is a tattoo machine. Only the medium differs: air or skin. Both transform frequency into', emphasis: 'lasting form.', alt: 'Blackwork tattoo transitioning into a sound wave', cue: 'tap / listen', mapping: [['Frequency', 'Line weight'], ['Amplitude', 'Contrast / Fill'], ['Rhythm', 'Repetition & Pause'], ['Silence', 'Negative space']], metrics: [['20 Hz – 20 kHz', 'audible spectrum'], ['∞', 'stays on the skin'], ['1 → 2', 'one signal, two media']] },
    analyse: { label: 'Analysis', title: 'The spectrogram as a design brief', intro: 'We read a spectrogram not as decoration, but as a blueprint. Every frequency zone becomes a design decision: density, line, rhythm and negative space.', bands: [['01 · LOW', 'Bass / Foundation', 'Heavy, extended forms. Broad lines, large fields — the outer contour in blackwork.'], ['02 · MID', 'Body / Character', 'Rhythm and texture. Repetition, modulation — this is where the brand’s “sound” emerges.'], ['03 · HIGH', 'Detail / Brilliance', 'Fine peaks and highlights. Thin lines, restrained accents.']] },
    shape: { label: 'New Branch · 2026', title: 'SHAPE YOUR SOUND', intro: 'One of our newest directions. We visualize each client’s sonic character and build systems for covers, motion, stage and identity.', alt: 'Visual identity system built from spectrogram shapes, covers and motion frames', cards: [['VISUAL SOUND', 'Make sound visible', 'Spectrogram → form. Waveforms and frequency spaces for visual identity.'], ['FORM + SYSTEM', 'Form and system', 'From a single release to an artist’s complete visual world.']], pillars: [['01 · Music', 'Living sound\nand its audience', 'Release strategies, visual systems, concerts and community around an artist or label.'], ['02 · Art & Creativity', 'A framework\nfor the artist', 'From manifesto to a resilient community. Speak clearly and bring the right people together.']] },
    dna: { label: '[ System DNA ]', people: [['DEVELOPER · I/TD', 'imtryingtodesign', 'Technical architecture and design system. Builds the structured site — systems that hold performance and form together.', 'imtryingtodesign.com →'], ['SPIRITUAL EXPEDITOR', 'NAMENLOS TATTOO', 'Breaks things into components to assemble them anew. Raw and precise — taking apart what will later live as a whole on skin.', 'NAMENLOS →']] },
    contact: { label: 'Contact', title: 'A release, sound or form?', intro: 'Tell us what you create. We reply within', hours: '24 hours.', received: 'Signal received', thanks: 'Thank you — we’ll read your spectrogram and get back to you within 24 hours.', name: 'Name / Project', namePlaceholder: 'Artist, label or release', email: 'Email', message: 'Message', messagePlaceholder: 'Tell us about your sound…', send: 'Send enquiry →' },
    footer: { aria: 'Footer navigation', links: ['Sound ↔ Skin', 'Spectrogram', 'DNA', 'Contact'] },
  },
  ru: {
    nav: { sound: 'Звук ↔ Кожа', spectrum: 'Спектрограмма', shape: 'ФОРМА', dna: 'ДНК', contact: 'Контакты', start: 'Начать проект', aria: 'Основная навигация', language: 'Выбрать язык' },
    hero: { eyebrow: 'SHAPE YOUR SOUND', arts: 'Музыка · Искусство · Форма звука', audience: 'Для музыкантов и лейблов', title: 'Мы делаем звук', titleEnd: 'видимым', signal: '01 · Сигнал', frequency: 'Частота', alt: 'Абстрактная спектрограмма с частотными полосами и звуковыми волнами', intro: 'Агентство для артистов и лейблов. Мы читаем спектрограммы, разбираем частоты и придаём звуку', emphasis: 'форму, которая остаётся.', discuss: 'Обсудить проект →', spectrum: 'Спектрограмма' },
    process: { label: '[ Наш процесс ]', title: 'От сигнала к волне', intro: 'Три движения, один непрерывный сигнал — от первого анализа до живого сообщества.', steps: [ ['01', 'Слушать / Читать', 'Читаем звук и спектрограмму. Слышим его характер прежде, чем появится хоть одна линия.', 'Анализ'], ['02', 'Разобрать и сформировать', 'Разбираем частоты и образ, затем собираем их в устойчивую форму.', 'Система'], ['03', 'Запустить волну', 'Система, контент и сообщество становятся движением.', 'Релиз'] ], accent: 'ОТ ТЕБЯ\nДЛЯ ВСЕХ.' },
    sound: { label: 'Звук ↔ Кожа', title: 'Татуировка и звуковая волна', subtitle: 'Обе оставляют след вибрации', body: 'Звук — это организованная вибрация. Тату-машинка тоже. Различается лишь материал: воздух или кожа. И то и другое превращает частоту в', emphasis: 'устойчивую форму.', alt: 'Блэкворк-татуировка, переходящая в звуковую волну', cue: 'нажми / слушай', mapping: [['Частота', 'Толщина линии'], ['Амплитуда', 'Контраст / Заливка'], ['Ритм', 'Повторение и пауза'], ['Тишина', 'Негативное пространство']], metrics: [['20 Гц – 20 кГц', 'слышимый спектр'], ['∞', 'остаётся на коже'], ['1 → 2', 'один сигнал, две среды']] },
    analyse: { label: 'Анализ', title: 'Спектрограмма как дизайн-бриф', intro: 'Мы читаем спектрограмму не как декор, а как чертёж. Каждая частотная зона становится дизайн-решением: плотностью, линией, ритмом и пустотой.', bands: [['01 · LOW', 'Бас / Основа', 'Тяжёлые, протяжённые формы. Широкие линии и крупные плоскости — внешний контур в блэкворке.'], ['02 · MID', 'Тело / Характер', 'Ритм и текстура. Повторение и модуляция — здесь рождается «звучание» бренда.'], ['03 · HIGH', 'Деталь / Блеск', 'Тонкие пики и блики. Деликатные линии, сдержанные акценты.']] },
    shape: { label: 'Новое направление · 2026', title: 'SHAPE YOUR SOUND', intro: 'Одно из наших новых направлений. Мы визуализируем характер звучания клиента и создаём системы для обложек, моушена, сцены и айдентики.', alt: 'Визуальная система идентичности из спектрограммных форм, обложек и моушен-кадров', cards: [['ВИЗУАЛЬНЫЙ ЗВУК', 'Сделать звук видимым', 'Спектрограмма → форма. Волны и частотные пространства для визуальной идентичности.'], ['ФОРМА + СИСТЕМА', 'Форма и система', 'От одного релиза до целостного визуального мира артиста.']], pillars: [['01 · Музыка', 'Живой звук\nи его аудитория', 'Релизные стратегии, визуальные системы, концерты и сообщество вокруг артиста или лейбла.'], ['02 · Искусство и творчество', 'Среда\nдля артиста', 'От манифеста до устойчивого сообщества. Говорить ясно и собирать вокруг себя тех, кому это близко.']] },
    dna: { label: '[ ДНК системы ]', people: [['РАЗРАБОТЧИК · I/TD', 'imtryingtodesign', 'Техническая архитектура и дизайн-система. Создаёт структурированный сайт — систему, объединяющую производительность и форму.', 'imtryingtodesign.com →'], ['ДУХОВНЫЙ ПРОВОДНИК', 'NAMENLOS TATTOO', 'Разбирает на компоненты, чтобы собрать заново. Грубо и точно — разделяет то, что позже станет единым целым на коже.', 'NAMENLOS →']] },
    contact: { label: 'Контакты', title: 'Релиз, звук или форма?', intro: 'Расскажи нам, что ты создаёшь. Ответим в течение', hours: '24 часов.', received: 'Сигнал получен', thanks: 'Спасибо — мы прочитаем твою спектрограмму и ответим в течение 24 часов.', name: 'Имя / Проект', namePlaceholder: 'Артист, лейбл или релиз', email: 'Эл. почта', message: 'Сообщение', messagePlaceholder: 'Расскажи нам о своём звуке…', send: 'Отправить запрос →' },
    footer: { aria: 'Навигация в подвале', links: ['Звук ↔ Кожа', 'Спектрограмма', 'ДНК', 'Контакты'] },
  },
} as const

export type Copy = (typeof translations)[Locale]

type LocaleContextValue = { locale: Locale; setLocale: (locale: Locale) => void; copy: Copy }
const LocaleContext = createContext<LocaleContextValue | null>(null)

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('de')

  function setLocale(nextLocale: Locale) {
    document.documentElement.lang = nextLocale
    setLocaleState(nextLocale)
  }

  return <LocaleContext.Provider value={{ locale, setLocale, copy: translations[locale] }}>{children}</LocaleContext.Provider>
}

export function useLocale() {
  const context = useContext(LocaleContext)
  if (!context) throw new Error('useLocale must be used within LocaleProvider')
  return context
}
